-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 19:50:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atelie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atelie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atelie` DEFAULT CHARACTER SET utf8 ;
USE `atelie` ;

-- -----------------------------------------------------
-- Table `atelie`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atelie`.`funcionario` (
  `id_funcionario` INT(3) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atelie`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atelie`.`pagamento` (
  `id_pagamento` INT(2) NOT NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`id_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atelie`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atelie`.`cliente` (
  `id_cliente` INT(3) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telofone` VARCHAR(11) NOT NULL,
  `gola` FLOAT NULL,
  `busto` FLOAT NULL,
  `cintura` FLOAT NULL,
  `largura_ombro` FLOAT NULL,
  `manga` FLOAT NULL,
  `quadril` FLOAT NULL,
  `coxa` FLOAT NULL,
  `outros` TEXT(30) NULL,
  `id_funcionario` INT(3) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_funcionario_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_cliente_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `atelie`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atelie`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atelie`.`pedido` (
  `id_pedido` INT(3) NOT NULL AUTO_INCREMENT,
  `descricao` LONGTEXT NULL,
  `data_entrega` DATE NOT NULL,
  `status` VARCHAR(3) NULL,
  `id_cliente` INT(3) NOT NULL,
  `id_pagamento` INT(2) NOT NULL,
  `id_funcionario` INT(3) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_cliente1_idx` (`id_cliente` ASC),
  INDEX `fk_pedido_pagamento1_idx` (`id_pagamento` ASC),
  INDEX `fk_pedido_funcionario1_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `atelie`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_pagamento1`
    FOREIGN KEY (`id_pagamento`)
    REFERENCES `atelie`.`pagamento` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `atelie`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
